### ISSUE TITLE
[Feat] : Extend support for additional markdown features: tables, images, horizontal rules

### ISSUE THREAD

**Issue by JasrajChouhan** [Webb-orbit/demo#1]
### Enhancement Request

Currently, the markdown-to-HTML converter supports basic markdown syntax. However, it lacks support for additional features such as tables, images, and comprehensive horizontal rule detection. To improve the utility of the package, I propose extending support for these markdown features.

### Proposed Changes
- **Tables**: Convert markdown table syntax into HTML table elements.
- **Images**: Convert markdown image syntax into HTML image elements.
- **Horizontal Rules**: Improve support for different types of horizontal rules (---, ***, ___).

These enhancements will make the package more robust and versatile, allowing users to convert a broader range of markdown syntax into HTML.

**Comment by Webb-orbit** [comment]
Tables, Images and Horizontal line are updated and created
